name: Generate user.js

on:
  schedule:
    - cron: "0 0 * * 4"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set variables
        run: |
          sudo apt install wget -y
        shell: bash

      - name: Generate user.js
        run: |
          ./build.sh

      - name: Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: custom
          tag_name: custom
          draft: false
          prerelease: false
          files: |
            user.js
            user.cfg

