name: Generate user.js

on:
  schedule:
    - cron: "0 0 * * 4"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
          sudo apt install wget -y
        shell: bash

      - name: Generate user.js
        run: |
          ./build.sh

      - name: Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          with:
            files: |
              user.js
              user.cfg

